### ISSUE TITLE
Checklist for testing wrattler-examples deployments

### ISSUE THREAD

**Issue by nbarlowATI** [wrattler/wrattler-examples#16]
Lots of things can go wrong when using a new method for deploying wrattler / wrattler-examples.  Local deployments using docker-compose, and cloud-deployments using binder (either using repo2docker or our own dockerfile) can end up with different directories being mounted in different places for different services.  
Here are the things we should check (list to be extended as needed):
- [ ] Jupyterlab should launch
- [ ] When clicking on a `.wrattler` file in Jupyterlab, it should open it in wrattler (if it opens in plaintext it is likely that `wrattler-app.js` was unavailable or jupyterlab was not looking for it (extension not working) or looking for it in the wrong place (e.g. not using proxy when on binder).
- [ ] `dependency.wrattler` should work end-to-end.  This will show that the language services and datastore are working correctly, that the client has the right URL for them, and the language services have the right URL for the datastore.
- [ ] making a test python file with a simple function definition, and using it in a python cell via `%local test.py` should work.  This shows that both jupyterlab and the client have access to the same directory, and the client is able to serve files from there.
- [ ] Running something like `graphviz.wrattler` should work.  This will demonstrate that the client is able to find and load local javascript files such as `loader.js`.
- [ ] AI assistants should work - should be able to add a test assistant, give it an input dataframe, and the output dataframe should appear.  This demonstrates that the client has the right URL for the aI assistants, and the ai assistants have the right URL for the datastore.
